// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Projects\go\go-infra-adapters\pkg\storage\contracts\contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contracts "github.com/brunojet/go-infra-adapters/v3/pkg/storage/contracts"
	gomock "github.com/golang/mock/gomock"
)

// MockBucketAdapter is a mock of BucketAdapter interface.
type MockBucketAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockBucketAdapterMockRecorder
}

// MockBucketAdapterMockRecorder is the mock recorder for MockBucketAdapter.
type MockBucketAdapterMockRecorder struct {
	mock *MockBucketAdapter
}

// NewMockBucketAdapter creates a new mock instance.
func NewMockBucketAdapter(ctrl *gomock.Controller) *MockBucketAdapter {
	mock := &MockBucketAdapter{ctrl: ctrl}
	mock.recorder = &MockBucketAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBucketAdapter) EXPECT() *MockBucketAdapterMockRecorder {
	return m.recorder
}

// BucketName mocks base method.
func (m *MockBucketAdapter) BucketName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BucketName")
	ret0, _ := ret[0].(string)
	return ret0
}

// BucketName indicates an expected call of BucketName.
func (mr *MockBucketAdapterMockRecorder) BucketName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BucketName", reflect.TypeOf((*MockBucketAdapter)(nil).BucketName))
}

// GetObject mocks base method.
func (m *MockBucketAdapter) GetObject(ctx context.Context, key string, obj *contracts.BucketObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, key, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetObject indicates an expected call of GetObject.
func (mr *MockBucketAdapterMockRecorder) GetObject(ctx, key, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockBucketAdapter)(nil).GetObject), ctx, key, obj)
}

// HeadObject mocks base method.
func (m *MockBucketAdapter) HeadObject(ctx context.Context, key string, objInfo *contracts.ObjectInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadObject", ctx, key, objInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// HeadObject indicates an expected call of HeadObject.
func (mr *MockBucketAdapterMockRecorder) HeadObject(ctx, key, objInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObject", reflect.TypeOf((*MockBucketAdapter)(nil).HeadObject), ctx, key, objInfo)
}

// PutObject mocks base method.
func (m *MockBucketAdapter) PutObject(ctx context.Context, obj *contracts.BucketObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockBucketAdapterMockRecorder) PutObject(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockBucketAdapter)(nil).PutObject), ctx, obj)
}

// MockStorageAPI is a mock of StorageAPI interface.
type MockStorageAPI struct {
	ctrl     *gomock.Controller
	recorder *MockStorageAPIMockRecorder
}

// MockStorageAPIMockRecorder is the mock recorder for MockStorageAPI.
type MockStorageAPIMockRecorder struct {
	mock *MockStorageAPI
}

// NewMockStorageAPI creates a new mock instance.
func NewMockStorageAPI(ctrl *gomock.Controller) *MockStorageAPI {
	mock := &MockStorageAPI{ctrl: ctrl}
	mock.recorder = &MockStorageAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageAPI) EXPECT() *MockStorageAPIMockRecorder {
	return m.recorder
}

// NewBucket mocks base method.
func (m *MockStorageAPI) NewBucket(name string) (contracts.BucketAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBucket", name)
	ret0, _ := ret[0].(contracts.BucketAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewBucket indicates an expected call of NewBucket.
func (mr *MockStorageAPIMockRecorder) NewBucket(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBucket", reflect.TypeOf((*MockStorageAPI)(nil).NewBucket), name)
}
