// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/brunojet/go-infra-adapters/v3/internal/cdn/aws (interfaces: CloudFrontClient)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	cloudfront "github.com/aws/aws-sdk-go-v2/service/cloudfront"
	gomock "github.com/golang/mock/gomock"
)

// MockCloudFrontClient is a mock of CloudFrontClient interface.
type MockCloudFrontClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudFrontClientMockRecorder
}

// MockCloudFrontClientMockRecorder is the mock recorder for MockCloudFrontClient.
type MockCloudFrontClientMockRecorder struct {
	mock *MockCloudFrontClient
}

// NewMockCloudFrontClient creates a new mock instance.
func NewMockCloudFrontClient(ctrl *gomock.Controller) *MockCloudFrontClient {
	mock := &MockCloudFrontClient{ctrl: ctrl}
	mock.recorder = &MockCloudFrontClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudFrontClient) EXPECT() *MockCloudFrontClientMockRecorder {
	return m.recorder
}

// CreateKeyGroup mocks base method.
func (m *MockCloudFrontClient) CreateKeyGroup(arg0 context.Context, arg1 *cloudfront.CreateKeyGroupInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.CreateKeyGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateKeyGroup", varargs...)
	ret0, _ := ret[0].(*cloudfront.CreateKeyGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyGroup indicates an expected call of CreateKeyGroup.
func (mr *MockCloudFrontClientMockRecorder) CreateKeyGroup(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyGroup", reflect.TypeOf((*MockCloudFrontClient)(nil).CreateKeyGroup), varargs...)
}

// CreatePublicKey mocks base method.
func (m *MockCloudFrontClient) CreatePublicKey(arg0 context.Context, arg1 *cloudfront.CreatePublicKeyInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.CreatePublicKeyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePublicKey", varargs...)
	ret0, _ := ret[0].(*cloudfront.CreatePublicKeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePublicKey indicates an expected call of CreatePublicKey.
func (mr *MockCloudFrontClientMockRecorder) CreatePublicKey(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePublicKey", reflect.TypeOf((*MockCloudFrontClient)(nil).CreatePublicKey), varargs...)
}

// DeletePublicKey mocks base method.
func (m *MockCloudFrontClient) DeletePublicKey(arg0 context.Context, arg1 *cloudfront.DeletePublicKeyInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.DeletePublicKeyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePublicKey", varargs...)
	ret0, _ := ret[0].(*cloudfront.DeletePublicKeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePublicKey indicates an expected call of DeletePublicKey.
func (mr *MockCloudFrontClientMockRecorder) DeletePublicKey(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePublicKey", reflect.TypeOf((*MockCloudFrontClient)(nil).DeletePublicKey), varargs...)
}

// GetKeyGroup mocks base method.
func (m *MockCloudFrontClient) GetKeyGroup(arg0 context.Context, arg1 *cloudfront.GetKeyGroupInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetKeyGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKeyGroup", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetKeyGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyGroup indicates an expected call of GetKeyGroup.
func (mr *MockCloudFrontClientMockRecorder) GetKeyGroup(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyGroup", reflect.TypeOf((*MockCloudFrontClient)(nil).GetKeyGroup), varargs...)
}

// GetPublicKey mocks base method.
func (m *MockCloudFrontClient) GetPublicKey(arg0 context.Context, arg1 *cloudfront.GetPublicKeyInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.GetPublicKeyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPublicKey", varargs...)
	ret0, _ := ret[0].(*cloudfront.GetPublicKeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockCloudFrontClientMockRecorder) GetPublicKey(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockCloudFrontClient)(nil).GetPublicKey), varargs...)
}

// ListKeyGroups mocks base method.
func (m *MockCloudFrontClient) ListKeyGroups(arg0 context.Context, arg1 *cloudfront.ListKeyGroupsInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListKeyGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListKeyGroups", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListKeyGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeyGroups indicates an expected call of ListKeyGroups.
func (mr *MockCloudFrontClientMockRecorder) ListKeyGroups(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeyGroups", reflect.TypeOf((*MockCloudFrontClient)(nil).ListKeyGroups), varargs...)
}

// ListPublicKeys mocks base method.
func (m *MockCloudFrontClient) ListPublicKeys(arg0 context.Context, arg1 *cloudfront.ListPublicKeysInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.ListPublicKeysOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPublicKeys", varargs...)
	ret0, _ := ret[0].(*cloudfront.ListPublicKeysOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicKeys indicates an expected call of ListPublicKeys.
func (mr *MockCloudFrontClientMockRecorder) ListPublicKeys(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicKeys", reflect.TypeOf((*MockCloudFrontClient)(nil).ListPublicKeys), varargs...)
}

// UpdateKeyGroup mocks base method.
func (m *MockCloudFrontClient) UpdateKeyGroup(arg0 context.Context, arg1 *cloudfront.UpdateKeyGroupInput, arg2 ...func(*cloudfront.Options)) (*cloudfront.UpdateKeyGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateKeyGroup", varargs...)
	ret0, _ := ret[0].(*cloudfront.UpdateKeyGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKeyGroup indicates an expected call of UpdateKeyGroup.
func (mr *MockCloudFrontClientMockRecorder) UpdateKeyGroup(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeyGroup", reflect.TypeOf((*MockCloudFrontClient)(nil).UpdateKeyGroup), varargs...)
}
