// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Projects\go\go-infra-adapters\pkg\secret\contracts\contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contracts "github.com/brunojet/go-infra-adapters/pkg/secret/contracts"
	gomock "github.com/golang/mock/gomock"
)

// MockSecretAdapter is a mock of SecretAdapter interface.
type MockSecretAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockSecretAdapterMockRecorder
}

// MockSecretAdapterMockRecorder is the mock recorder for MockSecretAdapter.
type MockSecretAdapterMockRecorder struct {
	mock *MockSecretAdapter
}

// NewMockSecretAdapter creates a new mock instance.
func NewMockSecretAdapter(ctrl *gomock.Controller) *MockSecretAdapter {
	mock := &MockSecretAdapter{ctrl: ctrl}
	mock.recorder = &MockSecretAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretAdapter) EXPECT() *MockSecretAdapterMockRecorder {
	return m.recorder
}

// DiscardVersion mocks base method.
func (m *MockSecretAdapter) DiscardVersion(ctx context.Context, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscardVersion", ctx, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// DiscardVersion indicates an expected call of DiscardVersion.
func (mr *MockSecretAdapterMockRecorder) DiscardVersion(ctx, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscardVersion", reflect.TypeOf((*MockSecretAdapter)(nil).DiscardVersion), ctx, version)
}

// GetCurrent mocks base method.
func (m *MockSecretAdapter) GetCurrent(ctx context.Context) (*contracts.T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrent", ctx)
	ret0, _ := ret[0].(*contracts.T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrent indicates an expected call of GetCurrent.
func (mr *MockSecretAdapterMockRecorder) GetCurrent(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrent", reflect.TypeOf((*MockSecretAdapter)(nil).GetCurrent), ctx)
}

// GetVersion mocks base method.
func (m *MockSecretAdapter) GetVersion(ctx context.Context, version string) (*contracts.T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, version)
	ret0, _ := ret[0].(*contracts.T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockSecretAdapterMockRecorder) GetVersion(ctx, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockSecretAdapter)(nil).GetVersion), ctx, version)
}

// HealthCheck mocks base method.
func (m *MockSecretAdapter) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockSecretAdapterMockRecorder) HealthCheck(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockSecretAdapter)(nil).HealthCheck), ctx)
}

// Name mocks base method.
func (m *MockSecretAdapter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSecretAdapterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSecretAdapter)(nil).Name))
}

// PromoteVersion mocks base method.
func (m *MockSecretAdapter) PromoteVersion(ctx context.Context, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteVersion", ctx, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// PromoteVersion indicates an expected call of PromoteVersion.
func (mr *MockSecretAdapterMockRecorder) PromoteVersion(ctx, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteVersion", reflect.TypeOf((*MockSecretAdapter)(nil).PromoteVersion), ctx, version)
}

// SetVersion mocks base method.
func (m *MockSecretAdapter) SetVersion(ctx context.Context, payload *contracts.T, version string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVersion", ctx, payload, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetVersion indicates an expected call of SetVersion.
func (mr *MockSecretAdapterMockRecorder) SetVersion(ctx, payload, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVersion", reflect.TypeOf((*MockSecretAdapter)(nil).SetVersion), ctx, payload, version)
}
