// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Projects\go\go-infra-adapters\pkg\secret\contracts\contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	"github.com/brunojet/go-infra-adapters/pkg/secret/contracts"
	gomock "github.com/golang/mock/gomock"
)

// MockSecretAdapter is a mock of SecretAdapter interface.
type MockSecretAdapter[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockSecretAdapterMockRecorder[T]
}

// MockSecretAdapterMockRecorder is the mock recorder for MockSecretAdapter.
type MockSecretAdapterMockRecorder[T any] struct {
	mock *MockSecretAdapter[T]
}

// NewMockSecretAdapter creates a new mock instance.
func NewMockSecretAdapter[T any](ctrl *gomock.Controller) *MockSecretAdapter[T] {
	mock := &MockSecretAdapter[T]{ctrl: ctrl}
	mock.recorder = &MockSecretAdapterMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretAdapter[T]) EXPECT() *MockSecretAdapterMockRecorder[T] {
	return m.recorder
}

// DiscardVersion mocks base method.
func (m *MockSecretAdapter[T]) DiscardVersion(ctx context.Context, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscardVersion", ctx, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// DiscardVersion indicates an expected call of DiscardVersion.
func (mr *MockSecretAdapterMockRecorder[T]) DiscardVersion(ctx, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscardVersion", reflect.TypeOf((*MockSecretAdapter[T])(nil).DiscardVersion), ctx, version)
}

// GetCurrent mocks base method.
func (m *MockSecretAdapter[T]) GetCurrent(ctx context.Context) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrent", ctx)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrent indicates an expected call of GetCurrent.
func (mr *MockSecretAdapterMockRecorder[T]) GetCurrent(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrent", reflect.TypeOf((*MockSecretAdapter[T])(nil).GetCurrent), ctx)
}

// GetVersion mocks base method.
func (m *MockSecretAdapter[T]) GetVersion(ctx context.Context, version string) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, version)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockSecretAdapterMockRecorder[T]) GetVersion(ctx, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockSecretAdapter[T])(nil).GetVersion), ctx, version)
}

// HealthCheck mocks base method.
func (m *MockSecretAdapter[T]) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockSecretAdapterMockRecorder[T]) HealthCheck(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockSecretAdapter[T])(nil).HealthCheck), ctx)
}

// Name mocks base method.
func (m *MockSecretAdapter[T]) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSecretAdapterMockRecorder[T]) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSecretAdapter[T])(nil).Name))
}

// PromoteVersion mocks base method.
func (m *MockSecretAdapter[T]) PromoteVersion(ctx context.Context, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteVersion", ctx, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// PromoteVersion indicates an expected call of PromoteVersion.
func (mr *MockSecretAdapterMockRecorder[T]) PromoteVersion(ctx, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteVersion", reflect.TypeOf((*MockSecretAdapter[T])(nil).PromoteVersion), ctx, version)
}

// SetVersion mocks base method.
func (m *MockSecretAdapter[T]) SetVersion(ctx context.Context, payload *T, version string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVersion", ctx, payload, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetVersion indicates an expected call of SetVersion.
func (mr *MockSecretAdapterMockRecorder[T]) SetVersion(ctx, payload, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVersion", reflect.TypeOf((*MockSecretAdapter[T])(nil).SetVersion), ctx, payload, version)
}

// Usage: var mock SecretAdapter[MyType] = NewMockSecretAdapter[MyType](ctrl)
var _ contracts.SecretAdapter[any] = (*MockSecretAdapter[any])(nil)
