// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/brunojet/go-infra-adapters/pkg/secret/contracts (interfaces: SecretAPI,SecretAdapter)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	contracts "github.com/brunojet/go-infra-adapters/pkg/secret/contracts"
	gomock "github.com/golang/mock/gomock"
)

// MockSecretAPI is a mock of SecretAPI interface.
type MockSecretAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSecretAPIMockRecorder
}

// MockSecretAPIMockRecorder is the mock recorder for MockSecretAPI.
type MockSecretAPIMockRecorder struct {
	mock *MockSecretAPI
}

// NewMockSecretAPI creates a new mock instance.
func NewMockSecretAPI(ctrl *gomock.Controller) *MockSecretAPI {
	mock := &MockSecretAPI{ctrl: ctrl}
	mock.recorder = &MockSecretAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretAPI) EXPECT() *MockSecretAPIMockRecorder {
	return m.recorder
}

// NewSecret mocks base method.
func (m *MockSecretAPI) NewSecret(arg0 string) (contracts.SecretAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSecret", arg0)
	ret0, _ := ret[0].(contracts.SecretAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSecret indicates an expected call of NewSecret.
func (mr *MockSecretAPIMockRecorder) NewSecret(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSecret", reflect.TypeOf((*MockSecretAPI)(nil).NewSecret), arg0)
}

// NewSecretWithClient mocks base method.
func (m *MockSecretAPI) NewSecretWithClient(arg0 string, arg1 contracts.SecretClientAPI) (contracts.SecretAdapter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSecretWithClient", arg0, arg1)
	ret0, _ := ret[0].(contracts.SecretAdapter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSecretWithClient indicates an expected call of NewSecretWithClient.
func (mr *MockSecretAPIMockRecorder) NewSecretWithClient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSecretWithClient", reflect.TypeOf((*MockSecretAPI)(nil).NewSecretWithClient), arg0, arg1)
}

// MockSecretAdapter is a mock of SecretAdapter interface.
type MockSecretAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockSecretAdapterMockRecorder
}

// MockSecretAdapterMockRecorder is the mock recorder for MockSecretAdapter.
type MockSecretAdapterMockRecorder struct {
	mock *MockSecretAdapter
}

// NewMockSecretAdapter creates a new mock instance.
func NewMockSecretAdapter(ctrl *gomock.Controller) *MockSecretAdapter {
	mock := &MockSecretAdapter{ctrl: ctrl}
	mock.recorder = &MockSecretAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretAdapter) EXPECT() *MockSecretAdapterMockRecorder {
	return m.recorder
}

// GetCurrent mocks base method.
func (m *MockSecretAdapter) GetCurrent(arg0 context.Context) (*contracts.SecretValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrent", arg0)
	ret0, _ := ret[0].(*contracts.SecretValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrent indicates an expected call of GetCurrent.
func (mr *MockSecretAdapterMockRecorder) GetCurrent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrent", reflect.TypeOf((*MockSecretAdapter)(nil).GetCurrent), arg0)
}

// GetVersion mocks base method.
func (m *MockSecretAdapter) GetVersion(arg0 context.Context, arg1 string) (*contracts.SecretValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", arg0, arg1)
	ret0, _ := ret[0].(*contracts.SecretValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockSecretAdapterMockRecorder) GetVersion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockSecretAdapter)(nil).GetVersion), arg0, arg1)
}

// Name mocks base method.
func (m *MockSecretAdapter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSecretAdapterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSecretAdapter)(nil).Name))
}
