// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Projects\go\go-infra-adapters\pkg\cdn\contracts\contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contracts "github.com/brunojet/go-infra-adapters/v3/pkg/cdn/contracts"
	gomock "github.com/golang/mock/gomock"
)

// MockCdnAdapter is a mock of CdnAdapter interface.
type MockCdnAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockCdnAdapterMockRecorder
}

// MockCdnAdapterMockRecorder is the mock recorder for MockCdnAdapter.
type MockCdnAdapterMockRecorder struct {
	mock *MockCdnAdapter
}

// NewMockCdnAdapter creates a new mock instance.
func NewMockCdnAdapter(ctrl *gomock.Controller) *MockCdnAdapter {
	mock := &MockCdnAdapter{ctrl: ctrl}
	mock.recorder = &MockCdnAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCdnAdapter) EXPECT() *MockCdnAdapterMockRecorder {
	return m.recorder
}

// CreatePublicKey mocks base method.
func (m *MockCdnAdapter) CreatePublicKey(ctx context.Context, key contracts.CdnKey) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePublicKey", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePublicKey indicates an expected call of CreatePublicKey.
func (mr *MockCdnAdapterMockRecorder) CreatePublicKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePublicKey", reflect.TypeOf((*MockCdnAdapter)(nil).CreatePublicKey), ctx, key)
}

// EnsureKeyGroup mocks base method.
func (m *MockCdnAdapter) EnsureKeyGroup(ctx context.Context, name, keyID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureKeyGroup", ctx, name, keyID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureKeyGroup indicates an expected call of EnsureKeyGroup.
func (mr *MockCdnAdapterMockRecorder) EnsureKeyGroup(ctx, name, keyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureKeyGroup", reflect.TypeOf((*MockCdnAdapter)(nil).EnsureKeyGroup), ctx, name, keyID)
}

// HealthCheck mocks base method.
func (m *MockCdnAdapter) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockCdnAdapterMockRecorder) HealthCheck(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockCdnAdapter)(nil).HealthCheck), ctx)
}

// VerifyKeyInGroup mocks base method.
func (m *MockCdnAdapter) VerifyKeyInGroup(ctx context.Context, key contracts.CdnKey) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyKeyInGroup", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyKeyInGroup indicates an expected call of VerifyKeyInGroup.
func (mr *MockCdnAdapterMockRecorder) VerifyKeyInGroup(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyKeyInGroup", reflect.TypeOf((*MockCdnAdapter)(nil).VerifyKeyInGroup), ctx, key)
}
