// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cloudfront/aws/client.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCloudFrontAPI is a mock of CloudFrontAPI interface.
type MockCloudFrontAPI struct {
	ctrl     *gomock.Controller
	recorder *MockCloudFrontAPIMockRecorder
}

// MockCloudFrontAPIMockRecorder is the mock recorder for MockCloudFrontAPI.
type MockCloudFrontAPIMockRecorder struct {
	mock *MockCloudFrontAPI
}

// NewMockCloudFrontAPI creates a new mock instance.
func NewMockCloudFrontAPI(ctrl *gomock.Controller) *MockCloudFrontAPI {
	mock := &MockCloudFrontAPI{ctrl: ctrl}
	mock.recorder = &MockCloudFrontAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudFrontAPI) EXPECT() *MockCloudFrontAPIMockRecorder {
	return m.recorder
}

// CreateKeyGroup mocks base method.
func (m *MockCloudFrontAPI) CreateKeyGroup(ctx context.Context, name string, publicKeyIDs []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyGroup", ctx, name, publicKeyIDs)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyGroup indicates an expected call of CreateKeyGroup.
func (mr *MockCloudFrontAPIMockRecorder) CreateKeyGroup(ctx, name, publicKeyIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyGroup", reflect.TypeOf((*MockCloudFrontAPI)(nil).CreateKeyGroup), ctx, name, publicKeyIDs)
}

// CreatePublicKey mocks base method.
func (m *MockCloudFrontAPI) CreatePublicKey(ctx context.Context, name, publicKeyPem string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePublicKey", ctx, name, publicKeyPem)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePublicKey indicates an expected call of CreatePublicKey.
func (mr *MockCloudFrontAPIMockRecorder) CreatePublicKey(ctx, name, publicKeyPem interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePublicKey", reflect.TypeOf((*MockCloudFrontAPI)(nil).CreatePublicKey), ctx, name, publicKeyPem)
}
